### ISSUE TITLE
[Feature-Request] - Today Module

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#10]
I thought, we could create a module that eg in the morning you say the weather, the temperature, if you have an appointment, if yes with who..

For example: You get up in the morning, you said "Hello -Keyword-" and he answers you "Hello -yourname-, we are the -date- today it rains, the temperature outside is 15 degrees C, you have no appointment of planned, Have a nice day! " with more features of course ;)

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.
