### ISSUE TITLE
Visualizations for audio in/out

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#102]
To better understand what works and doesn't work with Naomi STT, it helps me to see the actual transcription of what Naomi understood you to say and the response. I have done this in the past in the mic module by just adding some print lines to the check_for_keyword, active_listen, and say procedures.

In the past, I have used a single less than (<) for passive listen/wait for keyword, a double less than (<<) for active listen, and a double greater than (>>) for say, but I could imagine also colorizing the output.

This helps me with STT training, and just understanding why Naomi responds the way it does sometimes, and it's entertaining to watch, especially when it is picking up background conversations.

This is a modification that I keep making in order to my own copies, so I'd like to just go ahead and add it as an official modification.

**Comment by redragonx** [comment]
Merged the pr #142
