### ISSUE TITLE
Wiki - Build and install openfst - Reference to checkconfig

### ISSUE THREAD

**Issue by architek** [NaomiProject/Naomi#104]
Hello,

The wiki references checkconfig [here](https://github.com/NaomiProject/Naomi/wiki/Installing-Pocketsphinx-and-Phonetisaurus#build-and-install-openfst ).

I'm not able to find this in raspbian or debian repository. Actually I can't find it anywhere.

Where can this binary be found? Or should the wiki be updated ?

**System** 
- Device:  Raspberry Pi + Laptop
- OS: Raspbian + Debian Buster

Thank you

**Comment by aaronchantrill** [comment]
Sorry, it was checkinstall not checkconfig. I was thinking of adding it and I guess I did accidentally add a line about it. Sorry. Removed.
