### ISSUE TITLE
Twitter integration - as an independent plugin 

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#12]
Probably be a good idea to have twitter work with this to...
Basic functionality:
Get twitters with '@username' mentions
Have ability to disable notifications (i.e. human sleep time)
Send twitter, with playback of twitter msg before posting. (don't need rouge posting to twitter)

**Comment by G10DRAS** [comment]
Look at https://github.com/G10DRAS/JasperModules
Twitter

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.
