### ISSUE TITLE
Missing `blessings` dependency declaration

### ISSUE THREAD

**Issue by exarkun** [NaomiProject/Naomi#121]
**Describe the bug**
Populate.py fails with a traceback:

```
$ ./Populate.py 
Traceback (most recent call last):
  File "./Populate.py", line 4, in <module>
    import naomi
  File "/home/pi/Naomi/naomi/__init__.py", line 2, in <module>
    from .__main__ import main
  File "/home/pi/Naomi/naomi/__main__.py", line 6, in <module>
    from . import application
  File "/home/pi/Naomi/naomi/application.py", line 12, in <module>
    from . import populate
  File "/home/pi/Naomi/naomi/populate.py", line 4, in <module>
    from blessings import Terminal
ImportError: No module named blessings
```

**To Reproduce**
* Checkout Naomi, naomi-dev branch
* pip install -r python_requirements.txt
* run Populate.py (as instructed by https://github.com/NaomiProject/Naomi/wiki/Naomi-Installation-steps#running-naomi)

**Expected behavior**
To be guided through the profile creation process

**Screenshots**

**System** 
- Device:  Raspberry Pi
- OS: Raspbian Stretch Lite
  - Updated recently ? Yes 
- Jasper Version: Naomi branch naomi-dev

**Comment by aaronchantrill** [comment]
Blessings is listed in python-requirements.txt, so I'm not sure why this would be an issue. Could you run pip install -r python-requirements.txt again and post the output?

**Comment by aaronchantrill** [comment]
Are you maybe working in two different virtual environments?

**Comment by exarkun** [comment]
Hm.  What I probably did was check out master, install requirements from there, then switch to the naomi-dev branch.

**Comment by aaronchantrill** [comment]
Okay, that makes sense. Closing. Thank you for testing and reporting.
