### ISSUE TITLE
Let naomi use a list for wakewords

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#124]
I think it would be fun to allow Naomi to respond to a list of wake words instead of a single wake word. A list like ["naomi", "gnomie", "computer", "glados", "hal", etc.]

It should be easy enough to add an intersection statement to mic.py and detect not only when any one of the wake words is spoken, but which one was (ones were) spoken, so Naomi can react differently to different wake words.

I'm thinking specifically of an "Alexa for the elderly" commercial on Saturday Night Live for an echo that would respond to anything vaguely similar to "Alexa" shouted in its direction.

Definitely a low priority request, but pretty easy to implement.

**Comment by TuxSeb** [comment]
@redragonx do you still working on it ?

**Comment by AustinCasteel** [comment]
Closing since [PR #217](https://github.com/NaomiProject/Naomi/pull/217) integrated the enhancement request. Thanks for the contribution!
