### ISSUE TITLE
New weather plugin: OpenweatherMap API

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#13]
Check out this out for another option for weather besides yahoo

Changing the current module to this one, it bring:

- Better features
- Other languages support

http://openweathermap.org/api
http://openweathermap.org/current
https://github.com/csparpa/pyowm

**Comment by G10DRAS** [comment]
Look at https://github.com/G10DRAS/JasperModules
OpenWeatherMap Module

**Comment by TuxSeb** [comment]
It work on the older version ? @G10DRAS

**Comment by G10DRAS** [comment]
Yes it works with old version, but for new version code can be taken from this module. Let me know if you face any difficulty, else I will do it over weekend.

**Comment by TuxSeb** [comment]
ok thank you ! :) i'll do it !
