### ISSUE TITLE
Naomi-setup.sh issues

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#136]
## Description
The naomi-setup.sh program has a couple of issues. 

First, you must install the libncurses5-dev package on raspbian before python can be built with support for the curses module.

Second, we ran into problems where people tried to run pip install -r python-requirements and ended up upgrading their pip and breaking it because it was no longer compatible with their system. It seems that the latest Ubuntu uses a gcc compiler that appears to break python, so best to stick with the distro packages.

Third, redragonx pointed out that we don't need the nano requirement for anything.

## Expected Behavior
After installing distro (apt) packages required for Naomi and building a separate python environment for Naomi, it should run Naomi and allow the user to start configuring it.

## Actual Behavior
After building the environment, it attempts to run Naomi.py, but is unable to run populate.py because the curses library has not been compiled into the python executable. Stops with an error message about "No module named _curses". Also, if the user is working in ubuntu and attempts to install the python packages from python_requirements.txt to their system python, it may corrupt their copy of pip.

## Possible Fix
Add libncurses5-dev to the list of apt install packages. Remove pip and nano from the list of python modules to be built.

## Steps to Reproduce
1. Download Naomi 2.2
2. execute ./naomi-setup.sh

## Context
I was attempting to install and run the Naomi program.

**Comment by AustinCasteel** [comment]
Issue resolved with pull requests listed above. Reopen if this issue comes about again.
