### ISSUE TITLE
Implementing multiple keyservers

### ISSUE THREAD

**Issue by redragonx** [NaomiProject/Naomi#145]
That is very possible, and it seems likely that problems will occur from time to time, just due to the fact that public keyservers go up and down. If you try that again on the same machine, does it work? This does not look like a bug, but the program operating as designed.

_Originally posted by @aaronchantrill in https://github.com/NaomiProject/Naomi/pull/143_

**Comment by redragonx** [comment]
It would be good to try another server if the first gets "no data". I can keep trying without success with keys.gnupg.net as shown below.

![screenshot_2019-01-08_08-57-50](https://user-images.githubusercontent.com/3073252/50842248-8359e300-1323-11e9-974c-d9269c81d27d.png)

**Comment by redragonx** [comment]
The keyserver pgp.mit.edu worked for me and seems to be more available. 

![screenshot_2019-01-08_09-06-47](https://user-images.githubusercontent.com/3073252/50842836-c8324980-1324-11e9-888c-c5383b637977.png)

**Comment by redragonx** [comment]
This issue is related to pr #143 and issue #140

**Comment by aaronchantrill** [comment]
I have added a second keyserver. I'm not sure how to test this since the first one always works for me, but this should work.

**Comment by redragonx** [comment]
For future reference, you can test things like this by adding the domain in /etc/hosts and put 127.0.0.1 as the ip. It'll redirect the url there. 

> I have added a second keyserver. I'm not sure how to test this since the first one always works for me, but this should work.

**Comment by redragonx** [comment]
Fix has been added in the pr #143
