### ISSUE TITLE
Put a warning in the naomi-dev branch that says something about Python 3

### ISSUE THREAD

**Issue by redragonx** [NaomiProject/Naomi#147]
It just occurred to me that we should make sure old and new developers are aware of the big switch from Python 2 to 3. We didn't give a fair warning or even a good job communicating this fact to the world besides a badge in the readme file. 

## Detailed Description
Until we fully merge the changes into the master branch, I think creating a bold title is a great idea, in the readme that says "We switched to Python 3" in the first line of the readme. Or something similar. Pinned issue?

## Context
This came to my attention of the issue #146 I'm sure other devs will get confused as well.

## Possible Implementation
Readme change, pinned issue, dev announcement on the website?

**Comment by aaronchantrill** [comment]
@gospodima you may need to redo the import with 
`pip3 install -r python-requirements.txt`
What are you running this on? Just asking out of curiosity.

**Comment by AustinCasteel** [comment]
Associated pull requests have been merged, closing. Reopen or create a new Issue if a related issue arises in the future.
