### ISSUE TITLE
Script to download and install everything.

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#15]
This is a nice thing to do for the community.

Basic outline for user experience:

If your starting fresh
Download pi image from raspberry burn to SD.

If you already have image or just got your pi running for the first time
1. Run a sh or bash script from wget to start install process of Jasper.
2. Wait for Jasper to ask for help in finial configurations. This runs populate.py that asks for gmail creds, location and other personal info for being a personal assistant.
3. System is configured and if you reboot the pi the jasper software restarts because its a service.
- I know there is a huge amount of steps between 1 and 2, and then more steps between 2 and 3.
- I will work on an advanced outline to explain it better.
- A later thing.. is to have a voice question and answer phase of the setup, instead of typing configuration.

**Comment by andweber** [comment]
I think it would be better to provide a nightly build and version images ready to use for the supported platforms, currently jasper has too many options and dependencies for users. 
It's far too complex to get it running.
