### ISSUE TITLE
projectnaomai.com is compromised currently.

### ISSUE THREAD

**Issue by Yamaha32088** [NaomiProject/Naomi#150]
The site certificate is invalid when going to https://projectnaomi.com/
I noticed that a couple of images and links are broken on the Github readme page as well. I can submit a pull request and correct the links, pointing them to the non HTTPS site or if you decide to update the certificate then nothing needs to change.

**Comment by AustinCasteel** [comment]
If you look at the respective repos for the site and documentation, everything is correct. I can even direct you to the build page, however there was an issue with our registrar and the domains within the account were compromised. All the domains on the account now point to different servers, naomi included. The odd thing was that they cloned the website with a scrapper and then put it up on their own server, thus making it appear as it is still up but at the same time braking some things.

I have removed all public facing links to the website that I can until it is resolved for security reasons. But that does not guarantee that people will stumble onto it by themselves. If you are needing any documentation or specific links to anything you can find everything in the docs & website repo and as always you can reach out here or in our discord community and we can direct you to the right place.

**Comment by Yamaha32088** [comment]
OK thanks for the heads up. I was hoping to get the pre-compiled version of Naomi for the raspberry pi so I can just flash the SD card. I joined the discord channel so I will reach out there for help. Thanks

**Comment by AustinCasteel** [comment]
For anyone that needs the site or documentation during the down time, you can use the [build site!](https://projectnaomi.netlify.com/)

> Note: external links to the naomi project domain will not work, but internal link do.

**Comment by AustinCasteel** [comment]
The website is now backup and running. At the time of writing everything has been switched back over to it. However, the readme images are delayed showing up.
