### ISSUE TITLE
Deepspeech module structure has changed

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#152]
## Description
On version 0.4.1 of deepspeech, the line "from deepspeech.model
import Model" has changed to just "from deepspeech import Model"

## Expected Behavior
If you have deepspeech installed, it should be recognized and used

## Actual Behavior
You get the following error message:
ImportError: No module named 'deepspeech.model'

## Possible Fix
Make it so that if the first method fails, the second method is used

## Steps to Reproduce
1. use pip3 to install deepspeech
2. change naomi's active stt engine to deepspeech
3. start Naomi
4. Say "Naomi" to enter active listening mode

## Context
This bug just means that deepspeech may not work even if you have it installed right now.

## Your Environment
Raspbian Stretch on Raspberry pi 3B+

**Comment by AustinCasteel** [comment]
[Associated PR #153](https://github.com/NaomiProject/Naomi/pull/153) approved and merged.
