### ISSUE TITLE
Encoding problem in hackernews plagin

### ISSUE THREAD

**Issue by gospodima** [NaomiProject/Naomi#155]
There is an error occured by me, when naomi tries to encode response from hacker-news site: ```UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 100: ordinal not in range(256)```

**Comment by aaronchantrill** [comment]
Is there a line number or backtrace or anything? I'm not getting this error, so I'm not sure where it is coming from, encoding the url to send or building the response text. Both are currently encoded as <type 'str'> so I'm not sure why it would choke on \u2013. I tried pulling the top 100 stories which included a number of unicode characters which it seemed to handle fine.

**Comment by gospodima** [comment]
@aaronchantrill 
For example it occurs in local_mic.py here:
https://github.com/NaomiProject/Naomi/blob/6e5629d55502c84515bc0f6fccd582d79cab23fc/naomi/local_mic.py#L29
So, I get an error when it tries to print the response.
I have dev-branch on my RPi now.
And I also noticed, that in local_mic.py "JASPER" is still hardcoded.

**Comment by aaronchantrill** [comment]
Okay, thanks. I'll take a look at it this afternoon.

**Comment by aaronchantrill** [comment]
Are you using the master repo? That one is not set up for python 3. When I am using the naomi-dev branch on python3 I'm not having a problem even when I force a u2013 character onto the end of the news story title.

**Comment by gospodima** [comment]
@aaronchantrill 
No, I am using dev-branch. Theoretically, I had some problems with dependencies for python 3 and the problem can be here, but I think everything should be fine there since I fixed dependencies during the solving another my issue (https://github.com/NaomiProject/Naomi/issues/146).

**Comment by aaronchantrill** [comment]
Are you using the "de_DE" locale here then? I can't figure out what's different between your setup and mine. The full stack trace really would help me. I'm testing in german now, and still not getting an error message.
```console
pi@naomitestvb:~/Naomi $ ./Naomi.py --local
************************************************************
*                    Naomi Assistant                       *
* Made by the Naomi Community, based on the Jasper Project *
* Source code available from                               *
*    https://github.com/NaomiProject/Naomi                 *
************************************************************
JASPER: Mein name ist, Naomi.
JASPER: Was kann ich für dich tun?
YOU: hacker
JASPER: Getting the top 4 stories from Hacker News...
JASPER: These are the current top stories... 1) Genode OS: A tool kit for highly secure special-purpose operating systems–... 2) On whether changes in bedroom CO2 levels affect sleep quality–... 3) If 5G Is So Important, Why Isn’t It Secure?–... 4) Intro to hacking MicroSD cards (2013)–
YOU: 
```

**Comment by gospodima** [comment]
@aaronchantrill 
I tested it with both languages: English and German. And in both cases I get the error. I will post here stack trace but I don't know when I will have an opportunity to do this.

**Comment by gospodima** [comment]
Hi @aaronchantrill 
There is full output:
```
./dev/Naomi-dev/Naomi.py --local
************************************************************
*                    Naomi Assistant                       *
* Made by the Naomi Community, based on the Jasper Project *
* Source code available from                               *
*    https://github.com/NaomiProject/Naomi                 *
************************************************************
JASPER: Mein name ist Naomi.
JASPER: Was kann ich für dich tun, Name?
YOU: Nachrichten
JASPER: Lade die aktuellen Nachrichten...
ERROR:naomi.conversation:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/dev/Naomi-dev/naomi/conversation.py", line 55, in handleForever
    plugin.handle(text, self.mic)
  File "/home/pi/dev/Naomi-dev/plugins/speechhandler/news/news.py", line 82, in handle
    mic.say(text)
  File "/home/pi/dev/Naomi-dev/naomi/local_mic.py", line 29, in say
    print("JASPER: %s" % phrase)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 72: ordinal not in range(256)
JASPER: Tut mir leid, ich konnte deine Anfrage nicht bearbeiten. Bitte versuche es später noch einmal.
YOU: hacker
JASPER: Getting the top 4 stories from Hacker News...
JASPER: These are the current top stories... 1) KABOOM in 180 lines of bare C++... 2) Most People With Addiction Grow Out of It (2014)... 3) Hacking PostgreSQL [pdf]... 4) C++ Modules Might Be Dead-On-Arrival
YOU: 
```
Today there is no problematic symbol in hacker, but in news the same problem.

**Comment by aaronchantrill** [comment]
Still not seeing it here, even after manually adding a u2013 to the end of every line spoken through line local-mic line 29:
```
$ ./Naomi.py --local
************************************************************
*                    Naomi Assistant                       *
* Made by the Naomi Community, based on the Jasper Project *
* Source code available from                               *
*    https://github.com/NaomiProject/Naomi                 *
************************************************************
JASPER: Mein name ist, Computer.–
JASPER: Was kann ich für dich tun?–
YOU: Nachrichten
JASPER: Lade die aktuellen Nachrichten...–
JASPER: Das sind die aktuellen Top-Nachrichten... 1) Bocholt/NRW: Drei junge Menschen sterben bei Unfall mit Viehtransporter - Region... 2) Streit um Feinstaub-Grenzwerte: Scheuer will Konsequenzen ziehen... 3) Dammbruch in Brasilien: Hoffnung auf Überlebende schwindet... 4) Peter Altmaier über Kohleausstieg: „Wir werden eine ganze Reihe von Gesetzen brauchen“–
YOU: hacker
JASPER: Getting the top 4 stories from Hacker News...–
JASPER: These are the current top stories... 1) Apple supplier shifts away from China... 2) The Personal Toll of Whistle-Blowing... 3) Show HN: X-spreadsheet – A JavaScript (canvas) spreadsheet for web... 4) Writing an OS in Rust: Advanced Paging–
YOU: stopp
JASPER: Bis bald, –
Terminated
```

I am also using the dev branch on python3 - which should have less issues with unicode encoding.

Can you start a python3 session and do something like:
```
$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```
I'm wondering if this will respond with latin-1 instead of utf-8 in your case. If so, then it sounds like you are running a version of python earlier than 3.5. Can you send me the result of:
```
$ python3 --version
Python 3.5.3
```
If you are running version 3.4 or earlier, you can supposedly set the encoding in python 3 using the PYTHONIOENCODING environment variable, although I have not verified this. In python 3.5 and above, it appears that all strings are converted to utf-8 by default and there is no longer any way to change that. Since we have targeted Naomi at python versions 3.5+ (the version that currently ships with Raspbian Stretch) this may be the issue.

You can try this as a workaround and let me know if it works:
```
$ PYTHONIOENCODING=utf-8 ./Naomi.py
```

**Comment by aaronchantrill** [comment]
@gospodima have you had a chance to check your version of python? Did the PYTHONIOENCODING env variable do anything?

**Comment by gospodima** [comment]
@aaronchantrill no, unfortunately I hadn't time to check it, but I am going to do this today in the afternoon.

**Comment by gospodima** [comment]
@aaronchantrill 
for `sys.getdefaultencoding()` and `python3 --version` I have the same output (`'utf-8'` and `Python 3.5.3`). But when I add u2013 symbol to the every line spoken through line local-mic line 29 and run Naomi with `PYTHONIOENCODING=utf-8 ./Naomi.py --local` I get this:
```
JASPER:â Mein name ist Naomi.
JASPER:â Was kann ich fÃ¼r dich tun, Dmytro?
```
without `PYTHONIOENCODING=utf-8` I get 
```
File "/home/pi/dev/Naomi-dev/naomi/local_mic.py", line 29, in say
    print("JASPER:\u2013 %s" % phrase)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 7: ordinal not in range(256)
```

**Comment by aaronchantrill** [comment]
Thank you. What do you get if you just type "locale" in your terminal? It looks like using UTF-8 with PYTHONIOENCODING=utf-8 is properly encoding to utf-8, but your terminal is set to display in Latin-1 which is why the utf-8 characters are displaying weird. I'll do some research. The base problem appears to be that the base websites (https://hacker-news.firebaseio.com and https://news.google.com/) appear to be using extended characters in their news feed. I'll see if I can just strip those out.

**Comment by aaronchantrill** [comment]
So I have gotten this far:
```
$ PYTHONIOENCODING=Latin-1 python3
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print(("Hello \u2013 you"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 6: ordinal not in range(256)
>>> print(("Hello \u2013 you").replace("\u2013","-"))
Hello - you
>>> print(("Hello \u2013 you").encode("latin-1","replace"))
b'Hello ? you'
>>> print(("Hello \u2013 you").encode("latin-1","ignore"))
b'Hello  you'
>>> print(("Hello \u2013 you").encode("latin-1","ignore").decode())
Hello  you
```
So I am able to replace certain characters with something more iso-8859-1 friendly, and just strip the rest out, so that part is basically solved (just do an "encode" with error="ignore" on the text from the web service using the user's currently selected encoding). However, I'm not sure the best way to handle this programmatically. I should have something for you to try tomorrow. Thanks for your patience. I've learned a lot about character encoding in Linux through this.

**Comment by redragonx** [comment]
A terminal should have multiple locales like this to prevent weird char issues like this. We should try that first before stripping anything that might be important in some articles.

My daily use terminal setup:
```
▶ locale 
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Comment by redragonx** [comment]
Fonts are also important. Do you have a lot of fonts?

**Comment by redragonx** [comment]
Try ```locale -a``` instead to see enabled locales.
```
▶ locale -a
C
en_US
en_US.iso88591
en_US.utf8
POSIX
```

As you can see I have en_US.iso88591 support.

https://wiki.archlinux.org/index.php/locale

**Comment by aaronchantrill** [comment]
Okay, thanks @redragonx I see what you are saying now.

I opened a virtual machine with a copy of Raspbian Stretch x86_32 on it and removed all the locales except "en_US.iso88591", then edited /etc/default/locale and changed it to
```
#  File generated by update-locale
#LANG=en_US.iso88591
LANGUAGE=en_US.iso88591
LC_ALL=en_US.iso88591
```
restarted the machine, then did:
```
pi@raspbianvb:~ $ locale -a
C
C.UTF-8
en_US
en_US.iso88591
POSIX
pi@raspbianvb:~ $ locale
LANG=
LANGUAGE=en_US.iso88591
LC_CTYPE="en_US.iso88591"
LC_NUMERIC="en_US.iso88591"
LC_TIME="en_US.iso88591"
LC_COLLATE="en_US.iso88591"
LC_MONETARY="en_US.iso88591"
LC_MESSAGES="en_US.iso88591"
LC_PAPER="en_US.iso88591"
LC_NAME="en_US.iso88591"
LC_ADDRESS="en_US.iso88591"
LC_TELEPHONE="en_US.iso88591"
LC_MEASUREMENT="en_US.iso88591"
LC_IDENTIFICATION="en_US.iso88591"
LC_ALL=en_US.iso88591
pi@raspbianvb:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> print("\u2013")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 0: ordinal not in range(256)
>>> quit()
pi@raspbianvb:~ $ PYTHONIOENCODING=utf-8 python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> print("\u2013")
â
>>> quit()
pi@raspbianvb:~ $ sudo raspi-config
Generating locales (this might take a while)...
  en_US.ISO-8859-1... done
  en_US.UTF-8... done
Generation complete.
pi@raspbianvb:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print("\u2013")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 0: ordinal not in range(256)
>>> quit()
pi@raspbianvb:~ $ PYTHONIOENCODING=utf-8 python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> print("\u2013")
â
>>> 
```
So unfortunately, just installing utf-8 does not appear to fix the issue.

**Comment by aaronchantrill** [comment]
@gospodima The easiest fix is simply to set your default locale in the terminal to utf-8.

Unfortunately, there are different ways to do that depending on which flavor of linux you are using. Do you need the terminal encoding set to Latin-1 for some reason? Was it the default for your system, or something you set up at some point and don't necessarily need at this point?

I'd like to get an idea how widespread these issues might become.

**Comment by aaronchantrill** [comment]
I do have some thoughts on a couple of ways it could be papered over within Naomi itself, also, if necessary.

**Comment by gospodima** [comment]
@aaronchantrill 
I have Raspbian and I didn't do anything additional with locale. I also have en_GB (not US) as locale. 
Now I switched in raspi-config from iso88591 to utf8 and after reboot everything works fine.

Thanks a lot for your help!
