### ISSUE TITLE
imp module is deprecated

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#158]
## Detailed Description

The imp module, which we are currently using in the naomi/pluginstore.py file for handling plugins is deprecated as of version 3.4 and will be removed from a future version of python. The imp module is also used by plugins/stt/snowboy-stt/snowboydetect.py which warns not to modify it directly since it was generated by SWIG.

## Context

This just means that at some point in the future, Naomi's plugin system will break, and right now the following warning is generated when the imp module is imported under python 3.7:
```
DeprecationWarning: the imp module is deprecated in favour of importlib;
see the module's documentation for alternative uses
```
It is not an issue at the moment. I think even the latest versions of Python still work fine using the imp module.

## Possible Implementation

In naomi/pluginstore.py, replace the lines:
```
mod = imp.load_module(module_name, None, plugin_directory,
    ("py", "r", imp.PKG_DIRECTORY))
```
with
```
spec = importlib.util.spec_from_file_location(
    module_name,
    plugin_directory + '/__init__.py'
)
mod = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = mod
spec.loader.exec_module(mod)
```
## Your Environment

* naomi-dev branch
* Python 3.7.2
* Arch Linux

**Comment by redragonx** [comment]
pr #159 closes this.
