### ISSUE TITLE
Remove comma from introduction

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#164]
## Description
When Naomi states its wakeword at the beginning of conversation.py, there is a comma between "My name is" and the wakeword, causing it to execute a dramatic pause while introducing itself.

## Expected Behavior
It should just say "My name is <wakeword>" without the pause

## Actual Behavior
It pauses, dramatically - "My name is ... <Wakeword>"

## Possible Fix
Just remove the comma

## Steps to Reproduce
1. Install Naomi
2. Define a wakeword in ~/.naomi/profile.yml
3. Start Naomi

## Context
This bug just annoys me. It will be very simple to fix.

## Your Environment
Raspberry Pi 3B+, Raspbian Stretch

**Comment by AustinCasteel** [comment]
Closing; issue fixed in [PR#168](https://github.com/NaomiProject/Naomi/pull/168). If issue arises again this can be reopened or a new issue can be made.
