### ISSUE TITLE
google stt plugin is broken 

### ISSUE THREAD

**Issue by olest** [NaomiProject/Naomi#166]
## Description

The google stt plugin is broken. I see two issues: 

1) the plugin has not been updated to python3. As far as I can see, only the call to urllib.urlencode() needs updating. 

2) more severely, the google speech API has changed and the API call as it is currently implemented return http status 400.

## Possible Fix
The documentation of the new google speech API is here: https://cloud.google.com/speech-to-text/docs/reference/rest/v1/speech/recognize

## Steps to Reproduce
Set "google" as active_stt in Naomi's config file

**Comment by olest** [comment]
Hi @aaronchantrill , I saw that your pull requests to my fork addressed  the problems that you had mentioned. Thanks for doing that. I believe this ticket is now completed. If there is anything else missing, please let me know and I will look into it.

**Comment by aaronchantrill** [comment]
Thanks for putting so much effort into this. I've been a little distracted for the last couple of days but look forward to merging these two pull requests. They are going to resolve a bunch of issues we have had for a while. I expect to have time to test everything and get it merged either later this evening or sometime tomorrow morning.

**Comment by aaronchantrill** [comment]
Resolved with PR #184 Fixing google stt plugin and #185 Unit tests for google stt plugin, updated docs and credentials json
