### ISSUE TITLE
Last flite voice option being cut off

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#169]
## Description
As I recall, the flite -lv command used to return an extra element to the list, and I would list the voices by dropping the first two elements and the last element. The last element may have been a CR. It seems like the CR is no longer showing up, so now I am dropping the last voice in the list, which happens to be my personal favorite, "slt".

## Expected Behavior

It should list all the flite voices:
Available voices: ['kal', 'awb_time', 'kal16', 'awb', 'rms', 'slt'].

## Actual Behavior

It lists all but the last voice:
Available voices: ['kal', 'awb_time', 'kal16', 'awb', 'rms'].

## Possible Fix

Currently, the command is using
```
voices = run_command.run_command(['flite', '-lv']).split(" ")[2:-1]
```
It needs to drop the first two words, which are "Voices Available:".
I'm not sure why the last word had to be dropped also, but it is now causing a problem.

## Steps to Reproduce

1. install Naomi
2. ./Naomi.py --repopulate

## Context

Trying to configure Noami.

## Your Environment

* Version used: dev
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): python 3.5.3
* Server type and version:  Raspberry Pi 3B+
* Operating System and version: Raspbian Stretch

**Comment by AustinCasteel** [comment]
Closing since it was handled in [PR #171](https://github.com/NaomiProject/Naomi/pull/171)
