### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by chrobione** [NaomiProject/Naomi#19]
Need to get benchmarks of how the system preforms to see how much growing room we have for expanding.  
Remember that target platforms:
- RPI2 B
- RPI2 B+
- RPI3 

Suggestions on how this benchmark should be done please chime in with your comments.

**Comment by G10DRAS** [comment]
As we know, users are already running/using Jasper on all 3 afore mentioned platforms. 
In my view bench-marking should be done on per custom plugin/module basis, which will be added to Jasper (core). 
It will be useful for users to know few details about the new plugin/module before installation or start using it, like:
1. Functions of  plugin/module.
2. What are the extra libs required and how much space they will take after installation.
3. Network usage. (Online or offline)
4. Memory consumption.
5. Any new daemon process started/need by plugin/module on the same box.
    (ex:- marry-tts server, home automation hub, mpd daemon, etc.......)

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.
