### ISSUE TITLE
Add gettext support to is_positive and is_negative in naomi/app_utils.py

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#223]
## Detailed Description

Right now the app_utils.is_positive() and app_utils.is_negative() methods use string literals to determine whether a phrase is positive or negative. Since people don't use the same words and terms to indicate positive or negative in French or German, this should be a gettext() string. This just requires adding i18n to app_utils and translating the string.

## Context

Right now this is only used in the naomi.commandline.commandline().simple_yes_no() method, so it is only important if someone has hand edited their profile and changed a flag from a boolean to a yes/no answer. However, these functions are supposed to be general ways of testing a positive or negative connotation in Naomi.

**Comment by fatkaratekid** [comment]
I'm on it

**Comment by aaronchantrill** [comment]
Thank you!

**Comment by aaronchantrill** [comment]
Let me know if you need any help.

**Comment by fatkaratekid** [comment]
You can checkout the pull request [draft](https://github.com/NaomiProject/Naomi/pull/226). 
To be honest, I had some difficulties getting it to run, so I skipped the things I didn't need when creating the profile. All tests have passed.
