### ISSUE TITLE
naomi-setup.sh fails to set up virtual environment on RPi2B

### ISSUE THREAD

**Issue by fracpete** [NaomiProject/Naomi#260]
`naomi-setup.sh` (Naomi-3.0.M16) fails to set up virtual environment on a RPi2B as user `pi`.

## Description
On a RPi2B based on `2020-02-13-raspbian-buster-lite.img`, the install script `naomi-setup.sh` fails to find an `activate` script in the virtual environment it created. However, there is such a script in the `/home/pi/.virtualenvs/Naomi/bin` directory.

Full output of `naomi-setup.sh`:

```bash
pi@naomi:~/Naomi $ ./naomi-setup.sh 
There are three methods to install Naomi:

1) Use virtualenvwrapper to create a virtual Python 3 environment
   for Naomi (recommended)
2) Download, compile, and install a local copy of Python for Naomi
   (may not work for some users)
3) Use your primary Python 3 environment (this can be dangerous
   and can break other software on your system. It is only
   recommended for machines you intend to devote to running Naomi,
   like a virtual machine or Raspberry Pi)
4) Exit without installing

Please select: 1
NAOMI_DIR = /home/pi/Naomi

Notice: this program is about to use sudo to run the following command:
  sudo apt-get update
Press 'q' to quit, any other key to continue: 

Hit:1 http://archive.raspberrypi.org/debian buster InRelease                     
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                  
Reading package lists... Done                                           

Notice: this program is about to use sudo to run the following command:
  sudo apt-get install gettext portaudio19-dev libasound2-dev -y
Press 'q' to quit, any other key to continue: 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gettext is already the newest version (0.19.8.1-9).
portaudio19-dev is already the newest version (19.6.0-1).
libasound2-dev is already the newest version (1.1.8-1+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
VirtualEnv setup
Making sure you have the latest python, pip, python3 and pip3 installed on your system

Notice: this program is about to use sudo to run the following command:
  sudo apt-get install python python-pip python3 python3-pip
Press 'q' to quit, any other key to continue: 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python is already the newest version (2.7.16-1).
python3 is already the newest version (3.7.3-1).
python-pip is already the newest version (18.1-5+rpt1).
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: virtualenvwrapper in /home/pi/.local/lib/python2.7/site-packages (5.0.0)
Requirement already satisfied: virtualenv>=20.0.4 in /home/pi/.local/lib/python2.7/site-packages (from virtualenvwrapper) (20.0.17)
Requirement already satisfied: virtualenv-clone in /home/pi/.local/lib/python2.7/site-packages (from virtualenvwrapper) (0.5.4)
Requirement already satisfied: stevedore in /home/pi/.local/lib/python2.7/site-packages (from virtualenvwrapper) (1.32.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (1.4.3)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (1.6.0)
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python2.7/dist-packages (from virtualenv>=20.0.4->virtualenvwrapper) (1.12.0)
Requirement already satisfied: filelock<4,>=3.0.0 in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (3.0.12)
Requirement already satisfied: importlib-resources<2,>=1.0; python_version < "3.7" in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (1.4.0)
Requirement already satisfied: distlib<1,>=0.3.0 in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (0.3.0)
Requirement already satisfied: contextlib2<1,>=0.6.0; python_version < "3.3" in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (0.6.0.post1)
Requirement already satisfied: pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" in /home/pi/.local/lib/python2.7/site-packages (from virtualenv>=20.0.4->virtualenvwrapper) (2.3.5)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /home/pi/.local/lib/python2.7/site-packages (from stevedore->virtualenvwrapper) (5.4.5)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /home/pi/.local/lib/python2.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv>=20.0.4->virtualenvwrapper) (4.0.2)
Requirement already satisfied: zipp>=0.5 in /home/pi/.local/lib/python2.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv>=20.0.4->virtualenvwrapper) (1.2.0)
Requirement already satisfied: singledispatch; python_version < "3.4" in /home/pi/.local/lib/python2.7/site-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv>=20.0.4->virtualenvwrapper) (3.4.0.3)
Requirement already satisfied: typing; python_version < "3.5" in /home/pi/.local/lib/python2.7/site-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv>=20.0.4->virtualenvwrapper) (3.7.4.1)
Requirement already satisfied: scandir; python_version < "3.5" in /home/pi/.local/lib/python2.7/site-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv>=20.0.4->virtualenvwrapper) (1.10.0)
sourcing virtualenvwrapper.sh
checking if Naomi virtualenv exists
Naomi virtualenv does not exist. Creating.
created virtual environment CPython3.7.3.final.0-32 in 2066ms
  creator CPython3Posix(dest=/home/pi/.virtualenvs/Naomi, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/pi/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
virtualenvwrapper.user_scripts creating /home/pi/.virtualenvs/Naomi/usr/local/bin/predeactivate
ERROR: Environment '/home/pi/.virtualenvs/Naomi' does not contain an activate script.
ERROR: Environment '/home/pi/.virtualenvs/Naomi' does not contain an activate script.
Something went wrong, not in virtual environment...
```

Content of `/home/pi/.virtualenvs/Naomi`:

```bash
pi@naomi:~/Naomi $ ll /home/pi/.virtualenvs/Naomi
total 12
drwxr-xr-x 2 pi pi 4096 Apr 16 14:46 bin
drwxr-xr-x 3 pi pi 4096 Apr 16 14:46 lib
-rw-r--r-- 1 pi pi  202 Apr 16 14:46 pyvenv.cfg
```

Content of `/home/pi/.virtualenvs/Naomi/bin`:

```bash
pi@naomi:~/Naomi $ ll /home/pi/.virtualenvs/Naomi/bin/
total 64
-rw-r--r-- 1 pi pi 2216 Apr 16 14:46 activate
-rw-r--r-- 1 pi pi 1435 Apr 16 14:46 activate.csh
-rw-r--r-- 1 pi pi 3066 Apr 16 14:46 activate.fish
-rw-r--r-- 1 pi pi 1751 Apr 16 14:46 activate.ps1
-rw-r--r-- 1 pi pi 1199 Apr 16 14:46 activate_this.py
-rw-r--r-- 1 pi pi 1157 Apr 16 14:46 activate.xsh
-rwxr-xr-x 1 pi pi  252 Apr 16 14:46 easy_install
-rwxr-xr-x 1 pi pi  252 Apr 16 14:46 easy_install3
-rwxr-xr-x 1 pi pi  252 Apr 16 14:46 easy_install-3.7
-rwxr-xr-x 1 pi pi  243 Apr 16 14:46 pip
-rwxr-xr-x 1 pi pi  243 Apr 16 14:46 pip3
-rwxr-xr-x 1 pi pi  243 Apr 16 14:46 pip-3.7
-rwxr-xr-x 1 pi pi  243 Apr 16 14:46 pip3.7
lrwxrwxrwx 1 pi pi   16 Apr 16 14:46 python -> /usr/bin/python3
lrwxrwxrwx 1 pi pi    6 Apr 16 14:46 python3 -> python
lrwxrwxrwx 1 pi pi    6 Apr 16 14:46 python3.7 -> python
-rwxr-xr-x 1 pi pi  230 Apr 16 14:46 wheel
-rwxr-xr-x 1 pi pi  230 Apr 16 14:46 wheel3
-rwxr-xr-x 1 pi pi  230 Apr 16 14:46 wheel-3.7
```

## Your Environment
* Version used: Naomi-3.0.M16
* Server type and version: RPi2 Model B
* Operating System and version: 2020-02-13-raspbian-buster-lite.img

**Comment by AustinCasteel** [comment]
First off thank you for trying Naomi and I would like to apologize for this issue. We recently stumbled across it and actually have a [PR](https://github.com/NaomiProject/Naomi/pull/253) dealing with said issue along with some other changes and fixes. Let me verify the PR is good to go and runs properly then I will merge in the changes.

**Comment by aaronchantrill** [comment]
Peter, so glad to see you. Thank you for checking out our project.

That is a strange error that we have been trying to deal with for the last couple of days. The problem seems to be the latest version of virtualenvwrapper. If you can uninstall virtualenvwrapper, then "pip install --user virtualenv virtualenvwrapper==4.8.4" that should get virtualenvwrapper up and running again. Alternatively, you can source the activate script directly ($ . ~/.virtualenvs/Naomi/bin/activate) to get into the Naomi virtual environment.

If you can, I would love to get some feedback on the latest version of the naomi-setup.sh script, which can be downloaded via "git clone -b naomi-setup https://github.com/aaronchantrill/Naomi.git" and already contains this fix. I've tested it on an up to date copy of Raspbian Buster on a Raspberry Pi, and also on a virtual machine running Ubuntu 18.04.

@AustinCasteel is reporting that he is having an issue installing the current version of mock (4.0.2) on python 3.5.3, so I assume for python < 3.6 you need to use mock 3.0.5 instead, which also seems to run fine on 3.7.3. You don't happen to know any pip-fu for dealing with this sort of situation, do you? I generally try to avoid setting python requirements.txt files to specific versions.

Thanks,
Aaron

**Comment by fracpete** [comment]
I can confirm that the installation was successful. However, with all the compilation going on, it took 8+ hours on my RPi2B running off an SDCard. Is all that compilation intended?

In terms of requirements: if you want reproducible builds, using specific versions for libraries is a must. I recently had a problem with opencv-python regularly where the 4.2.x version resulted in `double free or corruption (!prev)`, crashing the process at random times. Fixing it to a specific version (earlier) made the problem go away...

**Comment by aaronchantrill** [comment]
With the installation successful, were you able to populate the profile and get a response to a simple query like "Naomi, what time is it?"

I'll fix the libraries at the version I currently have running, and just try to keep them up to date. The problem I've had is that some people are still running Raspbian Stretch or even Jessie, and the python libraries that work with 3.7 may not work with 3.5 and vice versa. I think we have a requirement for Python 3.5 or above on the website, or at least we used to, so I should be able to focus on those versions. It sounds like the only issue @AustinCasteel was having when running Raspbian Stretch was mock, which is a little ironic since it is only part of the unittest system.

The compiling process generally takes me about 3 hours on a Raspberry Pi 3B.

I am just uploading a new copy of the Naobian image based on Raspbian Buster now so it will run on a Raspberry Pi 4 (which is what I'm currently running it on).

One project that I'd love to get to soon would be replacing Phonetisaurus with a G2P engine that is more standard, preferably something that could be installed directly from the repositories. Pocketsphinx and SphinxTrain are both available through apt, so that much time compiling just to get the G2P working seems a little excessive. I'm open to any suggestions. I'm hoping to eventually move beyond G2P dictionaries and train directly against the user's voice, picking up the accent and speaking style of the user.

I also recently got Pocketsphinx running on my Raspberry Pi 4 which doesn't produce great results but definitely has promise, considering it's just running against a general model. I'm pretty excited to start training it and see how it does with some additional restrictions.

**Comment by aaronchantrill** [comment]
Seems like what pip really needs is a way to select the latest version of a module based on the version of python it is being installed to, or at least a way to specify version information based on python version in the requirements file. Usually people go to great lengths to keep the API consistent between releases, so I wouldn't expect to have to worry about re-writing the calls to a module between versions, just getting the module installed.

**Comment by fracpete** [comment]
Sorry for the late reply, workload is a bit high at the moment and only found out just now that I need to have a USB microphone for RPi (arrives hopefully end of the week). Will report back once I have a full mic/speaker setup. Will also try to get DeepSpeech going, as the project has made significant progress in terms of speeding things up ([source](https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/)).

**Comment by aaronchantrill** [comment]
You need a usb microphone for the raspberry pi (the pi actually uses the microphone connector on the audio out to transmit a video signal, allowing you to use a cable popularized by the Zune player to output RCA type video. This is handy when using the sort of display that is used to add a rear-camera to a car as a Pi monitor, but a pain if you expect to be able to just plug in a headset and record audio).

A lot of webcams have an integrated microphone. All the ones I have tried have worked fine as a usb microphone with the Raspberry Pi, and those tend to be a lot more common than an actual usb microphone or usb sound card. You might have one tucked in a drawer.

My best usb microphone experience has been a small, usb powered conference phone (https://www.amazon.com/gp/product/B078RJK4FW) which includes both microphone and speakers and hardware audio cancellation that reduces the volume of what Naomi is saying, allowing Naomi to speak its own wake word without activating itself and me to continue to issue commands while Naomi is speaking (this requires setting the currently undocumented "listen_while_talking" value to True in profile.yml, or using the "--listen-while-talking" flag when launching). Having the speakers and mic using the same cord and not needing external power greatly simplifies the tangle of wires around my Pi.

Deepspeech has made significant progress at memory efficiency. It now runs fine on my Raspberry Pi 4B (I tried running it on a Raspberry Pi 3B+ a couple of years ago, but was unable to load the whole language model into memory and without a language model, it simply returned a string of raw phonemes). Running it on the Pi with the standard english models still produces less than stellar results, but I'm excited about writing a STTTrainer for the acoustic model, and also experimenting with customizing the language model using the speechhandler intents templates and possibly reducing the vocabulary.

**Comment by aaronchantrill** [comment]
Resolved by downgrading the version of virtualenvwrapper in pythonrequired.txt
