### ISSUE TITLE
Sound effects should use the same audio format as TTS

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#262]
## Detailed Description

Flite produces audio output that is formatted as mono 16 bit little endian at 16MHz, and this appears to be the format generally preferred for both generating and recording audio. The beep_hi.wav and beep_lo.wav files which are used for testing the audio system and providing signals to the user are recorded in 16 bit little endian format, but at 44.1MHz stereo rather than 16MHz mono.

## Context

The beep_lo.wav file is played to test whether the user's audio system appears to be set up correctly. The fact that this is playing at a different rate than virtually any other audio file Naomi plays means that it is possible for this test to succeed, but then for Naomi's output to fail.

## Possible Implementation

We could just load the current files into audacity, reduce the channels to 1 and change the frequency to 16MHz. We may also want to generate some custom tones. I don't know where these sound effects came from, but they sound uncomfortably close to those used by some other assistants to me.

## Your Environment

* Version used: naomi-dev
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Python 3.7.3
* Server type and version: Raspberry Pi 4B
* Operating System and version: Raspbian Buster

**Comment by sank8-2** [comment]
Hi I have changed the audio files to mono and frequency to 16MHz, but I still didn't get the second part. Shall I raise a PR for the audio files?

**Comment by aaronchantrill** [comment]
@sank8-2 please do issue a pull request. I'm not sure what second part you are referring to, but getting a pull request with those files in the correct format would be a big help. Sorry it's taken me so long to get back to you.

**Comment by sank8-2** [comment]
@aaronchantrill Second part I was referring to generation of custom tones.
Alright I'll raise a PR

**Comment by aaronchantrill** [comment]
Yes, generating custom tones isn't anything I would expect someone new to the project to do, but standardizing the audio out on 16000Hz 1channel 16bit will help.

**Comment by aaronchantrill** [comment]
Merged https://github.com/NaomiProject/Naomi/pull/428 - Closed
