### ISSUE TITLE
Introduce Home Assistant module

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#27]
hi guys, in the next release (the 0.2), we would add a Homme Assitant module, an awesome home automation platform that track diffenrents devices (Arduino included !) and control them ! 

 https://home-assistant.io/

**Comment by andweber** [comment]
I will have a Look.

One more general point. Currently it looks like j2f is adding plugins. That's different from the original jasper philosophie. I'm not against it, just pointing out. I guess there are various good plugins out there. But there should be an interface for selecting plugins needed.

**Comment by andweber** [comment]
@TuxSeb have you already thought about the implementation? Are you intending something like a remote for the homeassistant using the python API?

**Comment by TuxSeb** [comment]
Closing this issue ...
