### ISSUE TITLE
Joke plugin gets overridden

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#295]
## Description

Austin has added a couple of new joke plugins - "Dad Jokes" and "Chuck Norris Jokes". While troubleshooting another issue, I discovered an interesting effect, that requesting "Tell me a joke" activates the the "Dad Joke" plugin rather than the "Joke" plugin. I think this is because in the case of "Joke" there are three similar templates and a dissimilar template but in the "Dad Joke" there are only two similar templates. I think what is happening is that the words from the dissimilar template "make me laugh" is lowering the match with the "tell me a joke" template more than the lack of the "Dad" keyword is lowering the score of the Dad Joke plugin.

In a perfect world, since the Dad jokes and Chuck Norris jokes have a specific phrase associated with them other than "joke" leaving out any specific request should default to the plugin with the least requirements. I'll look into that later and see if I can get "Naomi, tell me a joke" to default to the joke plugin when using the default Naomi_tti intent parser.

As I recall, I was having a similar issue with the News/Hacker News plugins where "what's in the news" was defaulting to hacker news rather than just news. I added some logic to reduce the score if a keyword was missing, which should affect the lack of "Dad" (which appears in both templates for "Dad Jokes") more than the inclusion of a template filled with unrelated words.

## Expected Behavior

If there are three plugins with the following three templates:

* Tell me a joke
* Tell me a dad joke
* Tell me a chuck norris joke

and the user requests "Tell me a joke", the intent parser should match the first option, not the second, because the edit distance between the request and the first option is smaller.

Both Adapt and Padatious handle this specific instance correctly.

## Actual Behavior

Right now, the Naomi_TTI intent parser is matching the second option. Since the match is 100% between the first option and the request, that should be the strongest match regardless of any words from other templates that do not appear in the request.

## Steps to Reproduce

1. Install Naomi
2. Install the Dad Jokes plugin (`Naomi --install "Dad Jokes"`)
3. Ask Naomi "Naomi, tell me a joke"

## Context

This bug sometimes makes it impossible to activate a general plugin after installing a specific plugin which does a similar thing.

## Your Environment

* Version used: naomi-dev
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Python 3.7.3
* Server type and version: Raspberry Pi 4 w/4GiB ram
* Operating System and version: Raspbian Buster

**Comment by AustinCasteel** [comment]
Fixed with PR #296
