### ISSUE TITLE
Mozilla Deepspeech PyPi module is not available for x86

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#310]
## Description

The Mozilla Deepspeech module is currently included with the base install of Naomi. Any modules that are included with Naomi should include all the python modules and apt packages required to run.  Because of this, part of the naomi-setup.sh process involves using pip to download the deepspeech module from pypi. Unfortunately, the deepspeech module is only available on 64 bit x86 systems and ARM systems, but the Raspbian/Raspberry Pi OS for running on Macs and PC's is 32bit (probably because the ARM version of the OS is also 32bit). This causes naomi-setup.sh to fail when trying to set up Naomi on a Raspbian x86 desktop when it attempts to use pip to install the deepspeech module.

## Expected Behavior

Naomi should be set up and ready to run on x86_32 Raspbian desktop.

## Actual Behavior

The naomi-setup.sh program errors out with a message that the module "deepspeech" cannot be found.

## Possible Fix

The easiest way to resolve this would be to move the Deepspeech module into the NPE and put the fact that it does not work with x86_32 operating systems in the description. The other way this might possibly be resolved would be to build versions of the latest copy of deepspeech for the x86_32 architecture and make them available for x86_32 systems, but this would be a big job. The last possibility would be to update the documentation to encourage users who want to use Naomi in a virtual machine to use a 64 bit version of Debian rather than Raspberry Pi OS Desktop.

## Steps to Reproduce

1. Download and install Raspberry Pi OS Desktop on a Mac or PC
2. run naomi_setup.py
3. receive error message about not being able to locate a version of deepspeech for the system.

## Context

I was just trying to install Naomi on Raspberry Pi desktop.

## Your Environment

* Version used: naomi-dev
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Python 3.7.3
* Server type and version: VirtualBox virtual machine
* Operating System and version: Raspbian x86 Desktop
* Link to your project:

**Comment by AustinCasteel** [comment]
Sort of like our [CMUSphinx_standard_language_models](https://github.com/NaomiProject/CMUSphinx_standard_language_models) we could have a repo that just holds all of the various builds for Naomi so if your system needs it then it can git it.

**Comment by aaronchantrill** [comment]
Thanks for looking at this, @AustinCasteel. That is the example I was thinking of originally also, but deepspeech is really fussy to build and requires just the right version of Bazel and keeping that up to date would probably require more effort than I would want to have to deal with, especially since every version of the deepspeech module appears to be built for each minor version of python.

Is there a reason you prefer that? It sounds like the next version of Raspberry Pi OS on ARM will be 64 bit, so maybe the Desktop version will switch also.

**Comment by aaronchantrill** [comment]
It looks like the reason Mozilla Deepspeech is unavailable for x86 computers is because Tensorflow, which it is written in, is unavailable for x86 computers. So I think the best course of action right now is to move the Deepspeech plugin to the Naomi Plugin Exchange and allowing people to install it if they need it.

**Comment by aaronchantrill** [comment]
@AustinCasteel fixed this issue by moving the deepspeech plugin out of core and into the Naomi Plugin Exchange with pull request [320](https://github.com/NaomiProject/Naomi/pull/320)
