### ISSUE TITLE
Searching text no longer remains highlighted

### ISSUE THREAD

**Issue by gkiely** [NaomiProject/Naomi#323]
When I search for text it no longer stays highlighted as expected.

## Expected Behavior
Text should stay highlighted as expected.

## Actual Behavior
Text does not stay highlighted as expected

## Possible Fix
N/A

## Steps to Reproduce
1. Install Naomi
2. Create a .js file with some text
3. Search for that text
4. Text does not stay highlighted

## Context
Searching for a function

## Your Environment
* Mac: 10.11.6
* Sublime: 3.0, Build 3170

Video:
https://www.loom.com/share/9e56fd24a102467a9091bcf0a4bd0710

**Comment by gkiely** [comment]
Never mind, was related to typescript package.

**Comment by AustinCasteel** [comment]
@gkiely To be honest I am trying to figure out what you are talking about exactly. The only thing I can think of that would remotely have any connection would have to do with the website. But even so, the way the website is setup this still does not make sense. Even with it being an issue you solved, can you post the video again and explain in more detail so I can at least understand what the issue originally was.
