### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#35]
Hi guys ! , the goal is to update the dependencies of Jasper2fork, you can see them [HERE](https://requires.io/github/jasper2fork/j2f/requirements/?branch=jasper-dev)
don't forget to ...
- Test all (or a part)  the plugins with the news dependencies
- Update python_requirements.txt
- Make pull request ONLY on the dev branch
- Update the wiki if it's needed 
- Fix pep8 error 

Thanks  ;) !

**Comment by G10DRAS** [comment]
This is not an issue. Better move it to WiKi page.

**Comment by TuxSeb** [comment]
This is not an issue but an improvement that we should done @G10DRAS

**Comment by G10DRAS** [comment]
Also mentioned Hardware (RPi2/3,.....) and OS (Jessie/Wheezy/......) where you installed jasper and tested jasper, This is important as not all the libs are available uniformaly on all the plateforms.
