### ISSUE TITLE
Move Naomi.sh to .config directory

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#360]
## Description

We currently add a call to Naomi.sh to the end of ~/.bashrc to initialize the virtualenvwrapper environment so the user just has to type `workon Naomi` to get into the environment. Naomi.sh also creates a function in the user's bash shell which allows them to run Naomi by typing `Naomi` at the command prompt, rather than having to type `~/Naomi/Naomi.py`.

This is the only user file we are adding to the Naomi directory. Other than this one file, the user would be able to delete the Naomi directory and re-clone it and it would most likely run fine without rerunning the installer.

## Expected Behavior

Deleting and restoring the ~/Naomi directory should not affect the way Naomi runs.

## Actual Behavior

If the user deleted the Naomi folder and then clones it directly from Github, they will have to copy or move the Naomi.sh file to another folder first. Otherwise, they will get an error every time they start a bash session stating that ~/Naomi/Naomi.sh cannot be found.

## Possible Fix

Move the Naomi.sh file to ~/.config/naomi/Naomi.sh

## Context

Sometimes I need to reset my working directory by deleting it and re-cloning it from Github, and I would rather not have to go through the setup procedure again.

**Comment by AustinCasteel** [comment]
Seems reasonable, will get it done momentarily

**Comment by AustinCasteel** [comment]
Fixed with PR #361
