### ISSUE TITLE
Camera Capture 

### ISSUE THREAD

**Issue by imije** [NaomiProject/Naomi#384]
Is naomi capable of camera capturing and sending it to an email?

**Comment by aaronchantrill** [comment]
It could certainly be done, but Naomi does not currently have a plugin specifically for capturing an image and emailing it.

Naomi can email things, and depending on what you are trying to do, capturing an image might not be difficult.

What is the project you have in mind?

**Comment by aaronchantrill** [comment]
@imije I'm assuming you would like something like this. You ask Naomi to take your picture. Naomi responds with "Okay, say cheese". When you say "cheese" a picture is taken and emailed to you. Does this sound correct? It could be done, but someone would have to develop it. I am happy to provide support if you would like to work on this.

**Comment by imije** [comment]
@aaronchantrill hiii thank you for your responses, I'm sorry for late replies due to my busy sched. Yes ur right I was expecting naomi to capture images using voice command then send it to an email or cloud.

**Comment by aaronchantrill** [comment]
@imije sorry, I saw your response a while ago. I thought I had responded to it but hadn't. Sorry about that. Are you interested in writing this? How can I help you?

**Comment by aaronchantrill** [comment]
I think @imije has abandoned this request. I don't know exactly what they where trying to do or whether it would be helpful to anyone, so I am closing this issue.
