### ISSUE TITLE
japer-client vs j2f

### ISSUE THREAD

**Issue by jantos** [NaomiProject/Naomi#40]
Just stumbled over this here and was wondering why this exists? Is there a reason why this is separate from the jasper-client project?

**Comment by chrobione** [comment]
This projected started because of distasteful way that contributors were
treated and expelled.

**Comment by jantos** [comment]
Thx for the answer @chrobione, that sucks to hear.

**Comment by chrobione** [comment]
Yeah sucks even worse to be telling people why too.

So ours split was based off the dev branch that have multiple language
support started.

If you have any questions please feel free to ask.

**Comment by jantos** [comment]
I was just wondering which repository is better to use at the end? Based on activity and enhancements. I saw that this one here included snowboy and saw a few other differences.

**Comment by chrobione** [comment]
There is effort required for both repos, but I am partial to ours.

**Comment by TuxSeb** [comment]
I'm closing this issue ...
