### ISSUE TITLE
Nav Bar and Footer Implementation

### ISSUE THREAD

**Issue by NishantRana07** [NaomiProject/Naomi#422]
##Problem - 

Ui of current Navbar is Not that impressive and can be optimised 

##Feature -

Footer can be added with Social links and animations

Please assign it to me under hacktoberfest and devfest and I will start working asap

**Comment by aaronchantrill** [comment]
Hello @NishantRana07 - I'm not sure I understand what you are proposing. Can you give me more details?

Thank you,
Aaron

**Comment by Prithwi32** [comment]
@aaronchantrill i can work on this issue if it's still open, please assign ot to me under hacktoberfest

**Comment by aaronchantrill** [comment]
@Prithwi32 It is not open. I don't understand what is even being proposed exactly. If you would like to work on an issue, I would suggest https://github.com/NaomiProject/Naomi/issues/347 - there are about a dozen plugins that still need to be moved from the main Naomi to their own repositories. For each plugin to the moved, you can get a pull request for adding the plugin to the new repository (which I can create for you), another for removing it from the main Naomi repository, another for generating a readme.md file for the repository, and a fourth for adding the new repository to the plugins.csv file in the naomi-plugins repository. I'm happy to guide you through the process. It's a good way to learn about Naomi, as well as helping to resolve this issue.

**Comment by Prithwi32** [comment]
> @Prithwi32 It is not open. I don't understand what is even being proposed exactly. If you would like to work on an issue, I would suggest #347 - there are about a dozen plugins that still need to be moved from the main Naomi to their own repositories. For each plugin to the moved, you can get a pull request for adding the plugin to the new repository (which I can create for you), another for removing it from the main Naomi repository, another for generating a readme.md file for the repository, and a fourth for adding the new repository to the plugins.csv file in the naomi-plugins repository. I'm happy to guide you through the process. It's a good way to learn about Naomi, as well as helping to resolve this issue.

Okay let me know issues.... I'm ready to solve with ur guidance 🙌..
Thank you 😌

**Comment by aaronchantrill** [comment]
@Prithwi32 sorry it's taken so long for me to get back to you. If you install Naomi, you will see a bunch of error messages when it starts running that have to do with plugins that are currently included with the base install, but the base install does not install the packages that they rely on:
```
Plugin at '/home/jess/Naomi/plugins/stt/julius-stt' skipped! (Reason: Skipping julius, 'julius' executable not found)
Plugin at '/home/jess/Naomi/plugins/stt/google-stt' skipped! (Reason: google module not installed)
Plugin at '/home/jess/Naomi/plugins/stt/snowboy-stt' skipped! (Reason: Skipping snowboy, 'snowboydetect' module not installed)
Plugin at '/home/jess/Naomi/plugins/tts/ivona-tts' skipped! (Reason: Skipping ivona, 'pyvona' module not installed)
Plugin at '/home/jess/Naomi/plugins/tts/cereproc-tts' skipped! (Reason: Skipping cereproc, 'suds' plugin not installed)
Plugin at '/home/jess/Naomi/plugins/tts/pico-tts' skipped! (Reason: Skipping Pico, executable 'pico2wave' not found!)
Plugin at '/home/jess/Naomi/plugins/tts/mstranslator-tts' skipped! (Reason: Skipping mstranslator, "mstranslator" module not found)
Plugin at '/home/jess/Naomi/plugins/tts/festival-tts' skipped! (Reason: Skipping festival, executables "test2wave" and/or "festival" not found)
Plugin at '/home/jess/Naomi/plugins/tti/adapt_tti' skipped! (Reason: adapt module not found)
```
You could choose to move any of these into its own repository, but if you don't have a preference, I would like you to move the adapt_tti plugin.

I have created a new repository at https://github.com/NaomiProject/naomi-plugin-adapt-tti.git. The first thing I would like you to do would be to copy all the files from https://github.com/NaomiProject/Naomi/tree/naomi-dev/plugins/tti/adapt_tti to that repository and make a pull request, and then make a second pull request against the basic Naomi repository removing all those files from the repository. Once those are done and accepted, I will want you to use the NPE Generator at https://npeeditor.projectnaomi.com to generate a readme.md file for the new repository and also add a python_requirements.txt file with the only package being "adapt-parser". You can use the content at https://projectnaomi.com/plugins/ttis/Adapt/ to help write the readme contents. Finally, I would like you to enter a pull request at https://github.com/NaomiProject/naomi-plugins adding the new repository as a plugin that can be downloaded directly from Naomi using the `Naomi --install "Adapt TTI"` command.

You don't have to make all four pull requests, but please let me know if you are finished so I can either finish up or have someone else do it.

I'm very interested in hearing about your experience installing and running Naomi. I have made a few videos on the process of installing. They are pretty boring and not well done. I'm hoping eventually someone will help me with that. Here is the latest one:
https://www.youtube.com/watch?v=pVdE36beIvk
I'd like to improve the documentation in the next year, once I have finished adding speaker recognition and local llm.

Thank you,
Aaron

**Comment by aaronchantrill** [comment]
Not going to implement.
