### ISSUE TITLE
Automatic Updating of Contributors Section via GitHub Action

### ISSUE THREAD

**Issue by amang876** [NaomiProject/Naomi#430]
I propose implementing a GitHub Action that automatically updates the "Contributors" section in the repository's README or CONTRIBUTORS file. This action would retrieve the latest list of contributors from the GitHub API and ensure the list is always current, minimizing manual maintenance efforts.

## Context
This change is important because maintaining an accurate list of contributors manually can be time-consuming and prone to errors, especially in large projects with frequent contributions. By automating this process, contributors will be consistently recognized for their efforts, enhancing project transparency and encouraging more contributions. Other users will benefit from having an up-to-date list of contributors, fostering a more inclusive and appreciative community.

## Possible Implementation
A possible implementation could involve creating a GitHub Action workflow that:

Triggers on a defined schedule (e.g., weekly) or specific events (e.g., after a pull request is merged).
Uses the GitHub API to fetch the current contributors.
Updates the README or CONTRIBUTORS file with the latest contributor information.
Optionally creates a pull request for review before merging changes to the main branch.

## Your Environment

Version used: N/A (Feature Request)
Environment name and version: N/A
Server type and version: N/A
Operating System and version: N/A
Link to your project: [Your Project Repository URL]

**Comment by aaronchantrill** [comment]
@SagarSharma101 thank you for taking the time to create this issue.

There already is an update-authors.sh script in the root of Naomi for this purpose. If you want, you can run this program and make a pull request with the updated AUTHORS.md.

Thank you,
Aaron

**Comment by amang876** [comment]
@aaronchantrill  actually i wanted to update the contributor section in readme of project automatically with help of github actions

![image](https://github.com/user-attachments/assets/9c4719a5-c7c3-494e-b43a-2d573fcf0de4)
here is an example

**Comment by aaronchantrill** [comment]
That's interesting. It looks like you've already done it. What is the mechanism? Is this something that would run automatically every time a new pull request is merged?

**Comment by amang876** [comment]
yes its using github action and we can change it whenever new contributor pushes changes to main branch

**Comment by aaronchantrill** [comment]
This was implemented, but not merged for right now. We might merge it later. For now, we are using opencollective to generate a list of contributors, but you can't just click on the icons to get to the contributor's profile.
