### ISSUE TITLE
[Feature-Request] - Passive Listening for commands 

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#48]
Instead of saying ‘Jasper’ then wait for a prompt, the user can now enable ‘passive mode’ in the config to enable Jasper to listen to commands and process them in 1 go. ‘Jasper tell me a joke’ will run the same as ‘Jasper?’ beep ‘Tell me a joke’ 

we could base our work on the following pull request: https://github.com/jasperproject/jasper-client/pull/434

**Comment by aaronchantrill** [comment]
Resolved in pull request [#181 Passive Listen](https://github.com/NaomiProject/Naomi/pull/181)

Needs a question in populate.py and documentation.
