### ISSUE TITLE
[Feature-Request] - Django/Tornado/NodeRed webapp

### ISSUE THREAD

**Issue by chrobione** [NaomiProject/Naomi#6]
Here are the thoughts:
- first time setup
- change configuration
- add module
- show info - local temp, OS stats, J2F stats, connected units

This is just a start we should brain storm on this first.

**Comment by chrobione** [comment]
Another suggested alternative might to use Tornado.

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.
