### ISSUE TITLE
Adding/updating STT engines

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#65]
* Update to the latest version of Phonetisaurus (requires the 1.6 version of OpenFST)
* Adding Mozilla's DeepSpeech engine

**Comment by aaronchantrill** [comment]
I have code for my version of Jasper that uses the latest git Phonetisaurus, which you must use if you install the latest OpenFST. It's mostly a matter of changing some parameters being passed in and switching the word list to lower case when performing the phoneme searches. I would like to incorporate those changes to g2p.py and sphinxvocab.py and push to Naomi.

**Comment by aaronchantrill** [comment]
I have written a Deepspeech STT plugin that I would like to incorporate. It currently does not run on a Raspberry Pi (the standard language model is 1.6 GiB and does not fit into the RPi ram, although I am working to figure out how to fix that). It is currently much slower than pocketsphinx, but allows you to have a much larger vocabulary while maintaining a decent word error rate. I would recommend using Pocketsphinx for passive recognition and Deepspeech for active recognition for those who are interested in playing with it.

**Comment by aaronchantrill** [comment]
Finished through updating the pocketsphinx plugin and adding the deepspeech-tts plugin.

**Comment by redragonx** [comment]
To use the lang model, we could see if we can stream the model from disk. I'm not good with Deepspeech yet though, so just an idea @aaronchantrill

**Comment by aaronchantrill** [comment]
Yes, @redragonx that would be my approach also. It also seems like we should be able to cut down the size of the model by limiting vocabulary some. I'm planning to dig into the deepspeech/tensorflow stuff right after I get training acoustic models in CMUSphinx working. I'd love to have someone to work with.
