### ISSUE TITLE
Adding/Updating TTS engines

### ISSUE THREAD

**Issue by AustinCasteel** [NaomiProject/Naomi#66]
• Adding the new [Google Cloud TTS](https://cloud.google.com/text-to-speech/)

**Comment by TuxSeb** [comment]
Very interesting and one the best engine by far, but you'll need a google cloud account to use it without a break

**Comment by AustinCasteel** [comment]
Understandable, the quotas aren't bad for the free tier and if someone wants to deploy Naomi on a larger scale they can pay for more.
