### ISSUE TITLE
Snowboy ships with precompiled library?

### ISSUE THREAD

**Issue by andweber** [NaomiProject/Naomi#7]
The STT plugin for snowboy includes a precompiled 32bit library. 

Is this limitation intended? Shouldn't the library be something downloaded on the fly / during install - instead of being included in the source code?

**Comment by chrobione** [comment]
I agree it should not ship with one:
- Give option to use precompiled one, or pull it down and compile.

**Comment by andweber** [comment]
can you please mark it as "bug" and "help wanted"

**Comment by TuxSeb** [comment]
it's done @andweber

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.
