### ISSUE TITLE
Add support for latest git version of Phonetisaurus

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#71]
The current version of Naomi (and Jasper) is not currently compatible with the latest Phonetisaurus. While I have no information that the latest phonetisaurus is significantly superior to the older version in terms of performance, I do know that the instructions for the older version require the user to download a file from https://www.dropbox.com/s/kfht75czdwucni1/g014b2b.tgz. I have no idea whose dropbox account this is, and would not want to count on it being available forever. The problem with compatibility between Naomi and the newer Phonetisaurus is that the Grapheme to Phoneme converter, phonetisaurus-g2p, has been split into phonetisaurus-g2pfst and phonetisaurus-g2prnn. Phonetisaurus-g2pfst is the logical successor to phonetisaurus-g2p, but no longer includes the --input command line option. It also relies on OpenFST 1.6.x, while the older version required OpenFST 1.3.x.

This update uses the instructions currently located at https://github.com/aaronchantrill/jasper-client/blob/master/PocketSphinx_setup.md (I will include that file with the pull request) and as far as I can tell, all the sources are stable releases direct from the maintainers. If anyone knows of a better source for one of these please let me know. These are all source code downloads, so the curious and security conscious can audit them. Unfortunately this means that it takes about 3 hours to compile everything on a Raspberry Pi.

I will test this on Raspbian Stretch running on a Raspberry Pi 3B and a Raspberry Pi 3B+ before issuing a pull request.

**Comment by G10DRAS** [comment]
Phonetisaurus (github version) is good.
1. Compile it using source code from github.
2. generate new FST (G2P Model) from cmudict.
3. Use this new G2P Model with phonetisaurus-g2pfst as follows
  ` phonetisaurus-g2pfst --model=cmudict.fst --nbest=1 --word=hello`
4. You will need to do some code changes in Jasper code as per above command.

**Comment by aaronchantrill** [comment]
This is done.
