### ISSUE TITLE
Extending Population

### ISSUE THREAD

**Issue by AustinCasteel** [NaomiProject/Naomi#73]
Taking what work aaronchantrill has done with [updating the population process.](https://github.com/NaomiProject/Naomi/pull/70). I would like to extend it further by addressing a couple concerns that where mentioned in [Issue #67](https://github.com/NaomiProject/Naomi/issues/67) as well as implementing a better UX.

By that I mean to formatting the questions better, rewording some of them, as well as changing the flow of the questions. So if you select a certain option for the config, if the next question references a previous answer you did not select it will skip over it. As well as fault tolerances so if you miss type something it will throw an error and ask again instead of defaulting and causing someone to start the whole process over again.

Finally adding in a styled CLI, so implementing colors & special characters to make the population process more enjoyable than what it actually is! 😄

**Comment by TuxSeb** [comment]
I think that would be the last improvement about `populate.py` before starting to write the **V.2.3** goals
