### ISSUE TITLE
Migrate to Python 3 soon.

### ISSUE THREAD

**Issue by redragonx** [NaomiProject/Naomi#90]
We shouldn't be supporting legacy versions of Python.

https://pythonclock.org/

**Comment by aaronchantrill** [comment]
Raspbian/Debian Stretch still use Python 2.7 as default. To use Python 3, you have to specify "python3" as the interpreter. In both pocketsphinx and deepspeech you are building tools for your specific version of python. To change from 2.7 to 3.5 currently requires remapping /usr/bin/python to /usr/bin/python3.5 and installing the python3-dev package. So at the moment it is more user friendly to use Python 2.7 than Python 3.5. As far as I know, Arch is the only distro that has embraced Python3 by making it the default.

I'm working on reinstalling on a fresh copy of Raspian and will try migrating to python3 at the same time.

**Comment by redragonx** [comment]
Don't forget that we have virtual env scripts to do this in 1 sec or so. Plus we can specifiy it with update-alteratives or use a bash startup to detect it too.

https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux

**Comment by aaronchantrill** [comment]
Well, changing the interpreter from "python2" to "python3" in Naomi.py isn't such a big deal. It's compiling some of the support modules that I'm working on. I'm working on a whole new walkthrough on installing pocketsphinx/phonetisaurus this weekend and working on two different methods, one where you compile everything from source as in my current guide and one where you use as many pre-built Debian/Raspbian packages as possible. That may not be such a big deal either.

**Comment by aaronchantrill** [comment]
Okay, I just started messing with this and am about to create a pull request on the new Naomi-dev branch. Still in early stages.

**Comment by abhiTronix** [comment]
@aaronchantrill @Longshotpro2  **Do we really need `Phonetisaurus`'s python bindings for this project during its installation?** https://projectnaomi.com/docs/plugins/pocketsphinx-install.html#build-and-install-phonetisaurus

_If yes, then it's only available for `Python-2.7` specifically, not for `Python-3`, **then we need a PR to fix that too?**_

**Comment by redragonx** [comment]
Closing this ticket as @aaronchantrill did the python3 branch and is now merged at #129 PR.
