### ISSUE TITLE
Fix Coveralls, Travis CI and Codacy

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#91]
**Describe the bug**

Theses dev tools currently doesn't work, they're all pointing to an other repository or a previous used name

**Comment by AustinCasteel** [comment]
Do note, the new read me has been updated to reflect the name & repo changes. But that being said, if the integration was never setup for naomi then the links wont work until they are.

**Comment by AustinCasteel** [comment]
After reviewing further, I pushed an update for the readme so now it is truly updated. Travis build fails, why the badge is errored. Coveralls needs to be updated, site is linked to the repo but there is no build for it to use currently. And finally Codacy is implemented and updated at least from what I can see.

**Comment by AustinCasteel** [comment]
Travis has now been removed for the time being. Closing this issue since all has been handled.
