### ISSUE TITLE
msgfmt: command not found

### ISSUE THREAD

**Issue by mrclemds** [NaomiProject/Naomi#92]
I have not been able to follow the installation process because it has been installed. That was causing msgfmt: command not found. Could you add it to the wiki?

**Comment by TuxSeb** [comment]
Hi, How can i reproduce this error ? on which file ? please provide more informations

**Comment by aaronchantrill** [comment]
It's at the ./compile_translations.sh point. It can be resolved by installing the "gettext" Raspbian package. So the line "sudo apt install git nano python-pip python-pyaudio python3-pyaudio" should be changed to "sudo apt install git nano python-pip python-pyaudio python3-pyaudio gettext" in the documentation/wiki. I have updated the Wiki. @Longshotpro2, could you copy the update to the ProjectNaomi.com website?

**Comment by AustinCasteel** [comment]
Website documentation updated!

**Comment by aaronchantrill** [comment]
Thanks @Longshotpro2 
@mrclemds, does this resolve this particular issue?

**Comment by mrclemds** [comment]
Yep thank you.
