### ISSUE TITLE
How should users get notifications?

### ISSUE THREAD

**Issue by redragonx** [NaomiProject/Naomi#93]
What are the ways we'd want to notify users?

Email
SMS
???

**Comment by TuxSeb** [comment]
Basically if there's a notification from any social network (Facebook, Twitter ...) the user should get the notification, Naomi should tell ya using TTS like "PPL liked your picture on SOCIAL_NETWORK"

It would be vocal notifications

**Comment by TuxSeb** [comment]
Here's an example of what you could do, based on a PR on the origial Jasper project https://github.com/jasperproject/jasper-client/pull/416
