### ISSUE TITLE
Move plugin specific settings into the plugin

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#98]
Right now, if you write a plugin with special settings (which weather service do you want? what is your email address? etc.) you either need to put those settings into "populate.py" manually, or just include a set of instructions for the user to update their profile.yml file.

To really be user friendly, I would like to have the plugin.info file that defines the plugin also list variables that need to be defined and, optionally, functions for requesting and validating them. When Naomi runs, it should look through all the plugins and find variables that need to exist but don't yet in the profile.yml file and walk the user through populating them.

This will allow developers to build plugins without modifying base files, and users to load and use new plugins without editing configuration files.

**Comment by redragonx** [comment]
There are a lot I would change about plugins. But we need to start simple. I agree with your thoughts, but I also think we should talk about putting settings in separate tables in a DB. This would make it easier to find a setting in a centralized area. Plus makes the GUI/terminal gui easier to manage.

plugin.info doesn't need anything  but the author info, etc.

**Comment by aaronchantrill** [comment]
I'd love to have your thoughts on what issues you would like to address with plugins. I'm happy they exist as such. They make a very convenient packaging system for this project. I have a lot of development experience but am just picking up Python now, so I don't know how standard the Naomi implementation is.

I don't feel like a full on relational database is really necessary right now given the small amount of data required for settings. I can imagine as we start building out a lexical database of the user(s) that it will eventually become necessary. But at the moment, flexible data structures such as YAML, XML, JSON, MongoDB, MUMPS, etc. seem more natural than forcing everything into a relatively flat table structure.

I'm not really following your thoughts on GUI, but I'm interested in hearing more about that. I'm just interested in coming up with a system flexible enough that the configuration requirements can be packaged directly in the plugin in a way that can be accessed before the plugin itself is loaded.

Anyway, I'm glad to hear that others are thinking along the same lines.

**Comment by aaronchantrill** [comment]
Having worked with some of the plugins, it seems like defining a standard function which can be called upon first loading a plugin to see if the plugin has been configured and then walking the user through the configuration if not should be easy enough to accomplish. Basically a "populate" function in each plugin.

**Comment by aaronchantrill** [comment]
Resolved in [PR#183 Replacement for weather plugin](https://github.com/NaomiProject/Naomi/pull/183)
